In [1]:
# pip install tensorflow==2.0.0-rc0
# pip install tensorflow-gpu==2.0.0-rc0

In [2]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense 

In [3]:
print(tf.__version__)

2.0.0-rc0


In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
import os

In [6]:
dataset = pd.read_csv('C:/Users/DELL/Desktop/Projects/KGP Talkie/Deep Learning/Building-Your-First-ANN-with-TensorFlow-2.0-master/Customer_Churn_Modelling.csv')

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
dataset.shape

(10000, 14)

In [9]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
X = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [11]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [12]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [13]:
#from sklearn.preprocessing import get_dummies

In [14]:
X = pd.get_dummies(X, drop_first=True, columns=['Gender', 'Geography'])
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Gender_Male  Geography_Germany  \
0               1        101348.88            0                  0   
1               1        112542.58            0                  0   
2               0        113931.57            0                  0   
3               0         93826.63            0                  0   
4               1         79084.10            0                  0   

   Geography_Spain  
0                0  
1                1  
2                0  
3                0  
4                1

## Feature Standardization 

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,  random_state = 0, stratify = y )

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

In [18]:
X_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
493           531   47       6       0.00              1          0   
6839          724   36       6   94615.11              2          1   
170           484   29       4  130114.39              1          1   
4958          655   37       6  109093.41              2          1   
4271          465   33       5       0.00              2          0   

      IsActiveMember  EstimatedSalary  Gender_Male  Geography_Germany  \
493                0        194998.34            0                  0   
6839               1         10627.21            1                  1   
170                0        164017.89            0                  0   
4958               0          1775.52            1                  0   
4271               1         78698.09            1                  0   

      Geography_Spain  
493                 0  
6839                0  
170                 0  
4958                0  
4271                0

In [19]:
y_train.head()

493     1
6839    0
170     0
4958    0
4271    0
Name: Exited, dtype: int64

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [21]:
X_train

array([[-1.24021723,  0.77986083,  0.35390313, ..., -1.09665089,
        -0.57812007, -0.57504086],
       [ 0.75974873, -0.27382717,  0.35390313, ...,  0.91186722,
         1.72974448, -0.57504086],
       [-1.72725557, -0.9443559 , -0.3390904 , ..., -1.09665089,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.87565065,  1.39339343, ...,  0.91186722,
         1.72974448, -0.57504086],
       [ 0.73902369, -0.36961699, -1.03208393, ..., -1.09665089,
        -0.57812007, -0.57504086],
       [ 0.95663657, -1.32751517,  0.35390313, ...,  0.91186722,
        -0.57812007,  1.73900686]])

### Build ANN

In [22]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation= 'sigmoid'))          

In [23]:
X.shape

(10000, 11)

In [24]:
X.shape[1]

11

In [25]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [26]:
y_pred = model.predict_classes(X_test)

In [27]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [28]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [30]:
confusion_matrix(y_test, y_pred)

array([[942, 651],
       [226, 181]], dtype=int64)

In [31]:
accuracy_score(y_test, y_pred)

0.5615